spring.application.name=bu_app
server.port=8081

# Configuración del contexto de la aplicación para que todas las rutas comiencen con /api
server.servlet.context-path=/bu-app

# Configuración de la base de datos H2 en memoria (EMBEDDED MODE)
# DB_CLOSE_DELAY=-1 evita que la BD en memoria se pierda si el pool cierra temporalmente conexiones.
# DB_CLOSE_ON_EXIT=FALSE evita cierre abrupto al finalizar JVM en algunos entornos.
spring.datasource.url=jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.h2.console.settings.web-allow-others=true

# Configuración del driver de la base de datos H2
spring.datasource.driver-class-name=org.h2.Driver

# Credenciales de la base de datos H2
spring.datasource.username=sa
spring.datasource.password=

# Configuración de JPA para crear y eliminar las tablas automáticamente al iniciar y cerrar la aplicación
spring.jpa.hibernate.ddl-auto=create-drop

# Habilitar la consola web de H2 para facilitar la visualización y manipulación de la base de datos en memoria
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuración para que la inicialización de la base de datos se realice después de que JPA haya creado las tablas 
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Dialect explícito para H2 (backup)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

app.jwt.secret=e0872510b3b486c8b7caa8fcfd0b62a19f28b2640e10d1cae0dc4341204644f2
# El tiempo de expiración del token JWT en milisegundos (1 hora)
app.jwt.expiration=3600000
