export const generateProgressReportHTML = (
    userName: string,
    weeklyData: number[],
    monthlyData: number[],
    totalWorkouts: number,
    currentStreak: number,
): string => {
    const currentDate = new Date().toLocaleDateString();

    return `
    <div style="font-family: Arial, sans-serif; padding: 20px; max-width: 800px;">
      <div style="text-align: center; margin-bottom: 30px; border-bottom: 2px solid #007bff; padding-bottom: 20px;">
        <h1 style="margin: 0; color: #333;">Progress Report</h1>
        <p style="color: #666; margin: 5px 0;">Generated on ${currentDate}</p>
      </div>

      <div style="margin-bottom: 20px;">
        <h2 style="color: #007bff; font-size: 18px;">User Information</h2>
        <p><strong>Name:</strong> ${userName}</p>
        <p><strong>Report Date:</strong> ${currentDate}</p>
      </div>

      <div style="margin-bottom: 20px;">
        <h2 style="color: #007bff; font-size: 18px;">Performance Metrics</h2>
        <table style="width: 100%; border-collapse: collapse; margin-bottom: 15px;">
          <tr style="background-color: #f5f5f5;">
            <td style="border: 1px solid #ddd; padding: 10px;"><strong>Metric</strong></td>
            <td style="border: 1px solid #ddd; padding: 10px;"><strong>Value</strong></td>
          </tr>
          <tr>
            <td style="border: 1px solid #ddd; padding: 10px;">Total Workouts</td>
            <td style="border: 1px solid #ddd; padding: 10px;">${totalWorkouts}</td>
          </tr>
          <tr style="background-color: #f9f9f9;">
            <td style="border: 1px solid #ddd; padding: 10px;">Current Streak (days)</td>
            <td style="border: 1px solid #ddd; padding: 10px;">${currentStreak}</td>
          </tr>
        </table>
      </div>

      <div style="margin-bottom: 20px;">
        <h2 style="color: #007bff; font-size: 18px;">Weekly Progress</h2>
        <p style="color: #666; margin: 0 0 10px 0;">Last 7 days average: ${(weeklyData.reduce((a, b) => a + b, 0) / weeklyData.length).toFixed(1)}%</p>
        <div style="display: flex; gap: 5px; align-items: flex-end; height: 150px; padding: 10px; background-color: #f9f9f9; border-radius: 4px;">
          ${weeklyData.map((value) => `<div style="flex: 1; height: ${value}%; background-color: #007bff; border-radius: 4px 4px 0 0; position: relative;"><span style="position: absolute; bottom: -20px; left: 0; right: 0; text-align: center; font-size: 12px;">${value}%</span></div>`).join('')}
        </div>
      </div>

      <div style="margin-bottom: 20px;">
        <h2 style="color: #007bff; font-size: 18px;">Monthly Progress</h2>
        <p style="color: #666; margin: 0 0 10px 0;">Monthly average: ${(monthlyData.reduce((a, b) => a + b, 0) / monthlyData.length).toFixed(1)}%</p>
        <div style="display: flex; gap: 5px; align-items: flex-end; height: 150px; padding: 10px; background-color: #f9f9f9; border-radius: 4px;">
          ${monthlyData.map((value) => `<div style="flex: 1; height: ${Math.min(value / 2, 100)}%; background-color: #28a745; border-radius: 4px 4px 0 0; position: relative;"><span style="position: absolute; bottom: -20px; left: 0; right: 0; text-align: center; font-size: 11px;">${value}%</span></div>`).join('')}
        </div>
      </div>

      <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #999; text-align: center;">
        <p>This is an automated report generated by the fitness platform.</p>
      </div>
    </div>
  `;
};
